mongodb/mongo-odbc-driver

- evergreen.yml
This is based off SQL-616 Because I needed code to test. It won't be merged until 616 is merged, so that we can have a clean gitlog. So the only changes that matter here are in evergreen.yml
> SQL-619: Add sanitizer tests

- Cargo.lock
- odbc/Cargo.toml
- odbc/src/api/driver_connect_tests.rs
- odbc/src/api/odbc_uri.rs
- resources/run_adf.sh
The spec can be found here: https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function?view=sql-server-ver16
the grammar suggests that {} is only allowed for the driver, but the text suggests it is allowed for any value, so that's what I went with.
({} is so that you can have special characters in a value... except obviously }).
> SQL-990: Properly handle the ODBC URI format

- integration_test/src/lib.rs
- integration_test/src/test_runner/mod.rs
- integration_test/tests/common/mod.rs
- resources/integration_test/tests/functions.yaml
- resources/integration_test/tests/queries.yaml
Implemented the query and function result set validation.  
There is still work to validate the column metadata, I will create a ticket to cover that. 
I have tested retrieving null and string data and added the query and function tests in `resources/integration_test/tests/queries.yaml|functions.yaml`.  I will test the numeric types before I merge. 
One area that could be improved is if there is a way to run the tests as a separate `#[test]` like in the connection tests [here](https://github.com/mongodb/mongo-odbc-driver/blob/master/odbc/tests/connection_tests.rs).  The issue is that the tests are run from integration_test() function, open to any suggestions.
> SQL-984: Test Harness: Implement Result Set validator

- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
I didn't do anything with the bson types that aren't C types because the spec is not clear what to do with those.
I'm also not sure what I did for date_time is right... because all it says is that we output data. Ok, that's great. What does that mean? I think it's easy to assume we just output the C struct (Timestamp) field by field, but should it be little endian or big endian? Who knows. I did little endian.
> SQL-1086: Audit and cleanup Binary handling

- odbc/Cargo.toml
- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
I've audited the tests, added more, and refined some error messages.
Per the spec (as I understand it), integer truncation is a "loss of the whole" and is an error rather than an Ok with a result and warning.
Interestingly, I'm getting intermittent test failures for test panic. Would appreciate a point out to where it might be.
```sh
cargo test --package mongo-odbc-driver --lib
...
failures:
---- api::panic_safe_exec_tests::unit::test_panic stdout ----
thread 'api::panic_safe_exec_tests::unit::test_panic' panicked at 'assertion failed: `(left == right)`
left: `"Panic(\"panic test\\nOk(\\\"in file '"`,
right: `"Panic(\"panic test\\nErr(RecvError)"`', odbc/src/api/panic_safe_exec_tests.rs:61:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures: …
```
> SQL-1093: audit to_x for i32, i64, u32, and u64

- odbc/src/api/data.rs
Adding bounds checking for to_f32. I looked at the rest of the logic (in `to_f64()`), and it looks correct.
> SQL-1094: add bounds checking for to_f32

- odbc/src/api/functions.rs
- odbc/src/api/util.rs
This PR uncomments the last `SQLGetInfoW` match case. As we know, this results in integration test memory failures, but these seem to be unrelated to this code directly so we could just override dependencies and get this into master anyway.
> SQL-1109: Finish SQLGetInfoW implementation

- core/src/collections.rs
- core/src/databases.rs
- core/src/fields.rs
- core/src/mock_query.rs
- core/src/query.rs
- core/src/stmt.rs
- core/src/table_types.rs
- core/src/util/decimal128.rs
- core/src/util/mod.rs
- odbc/src/api/col_attr_describe_tests.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
- odbc/src/api/env_attr_tests.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_diag_rec_tests.rs
- odbc/src/api/panic_safe_exec_tests.rs
- odbc/src/api/stmt_attr_tests.rs
- odbc/src/handles/definitions.rs
- odbc/src/handles/unit.rs
(also add Option<&MongoConnection> to next())
The impetus for this was actually that I needed to add MongoConnection to next to make the fields call (SQLColumns) not completely terrible, this way we can lazily get the schema info.
The other benefit is this will reduce lock contention. I don't think anything here will cause a deadlock, try to reason about that. But I think our biggest double lock holds are read on attributes with simultaneous write to errors. Nothing is trying to write to attributes and errors at the same time, so I think we should be good. 
Actually, most lock grabs now only exist for the span of one statement. But there are still a few to look at.
> SQL-1067: Refactor Mongohandle to use fine grain locking

- odbc/src/api/functions.rs
- odbc/src/handles/definitions.rs
- odbc/src/handles/unit.rs
Added initial infrastructure for descriptor handles. There are some pieces in the handle struct that aren't strictly necessary, but felt right given how other handles function and potential future additions (specifically, a reference to the dbc and a `state`).
> SQL-661: Initial support for descriptor handles

- integration_test/src/test_runner/mod.rs
- resources/integration_test/tests/functions.yaml
- resources/integration_test/tests/queries.yaml
Updates were made in the driver for the `REMARKS` column and values for nullability.  
This change updates the test files and allowing `SqlReturn::NO_DATA` from SQLGetData() (which is returned when the value is an empty string) to get the result set test to pass again.
> SQL-984: Test Harness - Update test and runner to work with driver changes

- integration_test/src/bin/test_generator.rs
- integration_test/src/lib.rs
- integration_test/src/test_runner/mod.rs
- integration_test/src/test_runner/test_generator_util.rs
This PR adds a test file generator executable which runs the integration tests in `resources/integration_test/tests` and writes the results to yaml files. This is heavily influenced by the JDBC test generator (shout out to @bucaojit 💯 ).
Caveats:
- `serde_yaml` is criminally underfeatured and does not support any formatting options. I looked into a few other libraries for formatting but those required quite a bit of overhead to get going and I didn't find any that could natively integrate with serde_yaml. I'm thinking when people generate tests, they can use a command line utility or built-in IDE/text-editor utility to format the generated yaml as desired.
- The `SqlDateType` to `CDataType` mapping is imperfect and possibly incorrect in places, so please take a close look at that!
- I …
> SQL-985: Implement test file generator

- Cargo.lock
- file_dbg_macros/Cargo.toml
- file_dbg_macros/src/lib.rs
- odbc/Cargo.toml
- odbc/src/api/data.rs
- odbc/src/api/functions.rs
- odbc/src/api/panic_safe_exec_tests.rs
This patch is based on @nbagnard 's tracing changes in this branch [branch](https://github.com/nbagnard/mongo-odbc-driver/tree/SQL-639-Playaround).
Sample output:
```
2023-01-05T19:41:20.764-08:00: odbc\src\api\functions.rs:1614 - "SQLGetData, SQLReturn = SUCCESS"
2023-01-05T19:41:20.765-08:00: odbc\src\api\functions.rs:1614 - "SQLGetData, SQLReturn = SUCCESS"
2023-01-05T19:41:20.766-08:00: odbc\src\api\functions.rs:1614 - "SQLGetData, SQLReturn = NO_DATA"
2023-01-05T19:41:20.767-08:00: odbc\src\api\functions.rs:1265 - "SQLFetch, SQLReturn = NO_DATA"
2023-01-05T19:41:20.768-08:00: odbc\src\api\functions.rs:1385 - "SQLFreeHandle, SQLReturn = SUCCESS"
2023-01-05T19:41:20.768-08:00: odbc\src\api\functions.rs:964 - "SQLDisconnect, SQLReturn = SUCCESS"
2023-01-05T19:41:20.769-08:00: …
```
> SQL-1156: Add SQL function tracing and output to logfile

- core/src/col_metadata.rs
- core/src/odbc_uri.rs
- core/src/util/decimal128.rs
- file_dbg_macros/src/lib.rs
- integration_test/src/bin/data_loader.rs
- integration_test/src/test_runner/mod.rs
- integration_test/src/test_runner/test_generator_util.rs
- integration_test/tests/common/mod.rs
- integration_test/tests/power_bi_tests.rs
- odbc/src/api/col_attr_describe_tests.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
- odbc/src/api/diag.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_info_tests.rs
- resources/integration_test/tests/functions.yml
- resources/integration_test/tests/sqltables.yml
This change fixes an issue seen in Power BI where no tables were being listed with the call:
```
SQLTablesW("%", 1, null, 0, null, 0, "TABLE,VIEW", 10)
```
Added a result set test to verify the sqltables call. 
There are quite a few clippy errors due to a change in Rust allowing variables in the format! string.  Will work on addressing that.
> SQL-1185: Fix SQLTablesW not listing table names

- constants/src/lib.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_info_tests.rs
- odbc/src/api/util.rs
I extracted the odbc version to a constant located with other constants.
Also, while I was lookihng at the test suite I noticed that we were hard coding a version expectation, even though we derive the driver version from our cargo.toml file. I updated the the associated tests.
> SQL-1176: corrects odbc version; updates driver version test

- core/src/bson_type_info.rs
- core/src/json_schema.rs
This PR resolves BsonTypeInfo for columns where the types are `AnyOf(Null, <other concrete>)`. I added two tests for both paths.
> SQL-1170: Resolve BsonTypeInfo

- odbc/src/api/functions.rs
This is a small change that fixes the handling of missing values.
> SQL-1188: Handle missing values

- file_dbg_macros/src/lib.rs
- odbc/src/api/data.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_info_tests.rs
- odbc/src/api/mod.rs
- odbc/src/api/panic_safe_exec_tests.rs
- odbc/src/api/util.rs
- odbc/src/handles/definitions.rs
I did a bit of refactoring to get the handle info and function name more easily in the trace.
The trace now look like this. It allows filtering per handle or function name.
```
2023-02-09T16:44:30.298-08:00 odbc/src/api/functions.rs:1470 - [Env_0x16d1c1fd0][Conn_0x16d1c21e0][Desc_0x144e05570] SQLFreeHandle:: Freeing handle 0x144e05570
2023-02-09T16:44:30.298-08:00 odbc/src/api/functions.rs:1475 - SQLFreeHandle:: SQLReturn = SUCCESS
2023-02-09T19:21:53.726-08:00 odbc/src/api/functions.rs:203 - SQLAllocHandle:: SQLReturn = SUCCESS
2023-02-09T19:21:53.736-08:00 odbc/src/api/functions.rs:203 - SQLAllocHandle:: SQLReturn = SUCCESS
2023-02-09T19:21:53.736-08:00 odbc/src/api/functions.rs:203 - SQLAllocHandle:: SQLReturn = SUCCESS
2023-02-09T19:21:53.737-08:00 odbc/src/api/functions.rs:203 - …
```
> SQL-1190: Add error messages to trace

- RELEASE.md
- evergreen.yml
In order for us to have the ability to provide a build with logging enabled if needed for EAP users, we need to have a debug build available.
This patch builds the debug version of the driver and upload it to our release bucket.
I also added the pdb in case we need them at some point too.
> SQL-1261: Build debug version of the driver and upload symbols for both

- Cargo.lock
- core/Cargo.toml
- core/src/conn.rs
- integration_test/Cargo.toml
- odbc/Cargo.toml
- odbc/src/api/functions.rs
Please see [JIRA](https://jira.mongodb.org/browse/SQL-1265) for additional context.
This PR proposes to add a 200ms wait time to allow the driver to clean up underlying resources prior to returning success and receiving a call to free the connection handle.
It also sizes the connection pool to 1, which will reduce resource consumption and shouldn't impact our operations because we're synchronous anyway.
@nbagnard and @pmeredit feel free assign/reassign reviewers. Tagged you both since you have most context.
> SQL-1266: Temporary workaround for intermittent segfault

- evergreen.yml
Fixed the error on the variable named used. 
Evergreen variables are not accessible directly from a shell task, so ${release-version} is empty.
> SQL-1261: Tag triggered release - Live trial error fixing

- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
This returns binary subtype 4 data in uuid form. In Power Bi, the user will still see it as Binary, but they can then transform it to text, then to JSON. The choice of "extended JSON" here is best intent to make it clear to the user what it is.
> SQL-1292: return binary subtype 4 as uuid

- README.md
Added all the function names that call the `unsupported_function!` macro to a table. I felt a bit unsure of the proper way to format, as this read the cleanest, but doubled the length of the README
> SQL-1282: add list of unsupported functions to README

- odbc/Cargo.toml
- odbc/build.rs
Adds product/version info, company name, and file names to mongoodbc.dll. A couple things to note:
1. the ticket mentions not necessarily using the `winres` crate as is. The current implementation does, as the crate is fairly lightweight, and covers what we are looking for out of the box. I also tried implementing this without the cate, but it requires some shared logic and/or hardcoding of paths.
2. relatedly, this does not use a template RC file, as generating one
with `winres` was only a few lines of code and executes quickly. However, with or without winres we could use a template to seed the values if desired.
Attached are a couple screenshots demonstrating the behavior of building using this branch:
> SQL-1296: Add the version informations to the Windows DLL

- core/src/util/mod.rs
An errant dbg made it through, this removes it.
> remove dbg

- core/src/json_schema.rs
The generated schema for a row with an empty array has no bsonType specified, it also has ` "additionalProperties": false`.  
This change takes into account the possible additionalProperties: false to avoid returning an error and instead return a `BsonTypeName::Any`.
```
{ "_id" : 0, "entry" : [ ] }
{ "_id" : 1, "entry" : [ ] }
```
Schema:
```
{  "bsonType": [ "object" ],
"properties": {
"_id": { "bsonType": [ "double"],  "additionalProperties": false},
"entry": {
"bsonType": [ "array"],
"items": {
"additionalProperties": false
},
"additionalProperties": false
}
},
"additionalProperties": false}
```
We currently don't log an error when this happens, there is an [existing PR](https://github.com/mongodb/mongo-odbc-driver/pull/92) to add the error message so I did not include one here.
> SQL-1337: Fix for Power BI error 'table has no visible columns'

- odbc/src/api/data.rs
- odbc/src/api/data_tests.rs
Some types were showing up as symbols in Power BI when processed with the `to_binary()` function.  This would mainly show up when the column had a type of anyof with multiple types such as Date, ObjectID, Null for example.
This PR returns those values as the JSON value which is readable in Power BI.
See [SQL-1325](https://jira.mongodb.org/browse/SQL-1325) for details and screenshots.
> SQL-1325: Fix for Power BI showing symbols instead of readable text

- evergreen.yml
Short one, just updating the snapshot task so we don't get a "system failed" when manually running it.
> add signing tasks as part of snapshot

- evergreen.yml
- odbc/src/api/util.rs
- resources/run_adf.sh
- setup/iodbc.ini
- shared_sql_utils/src/dsn.rs
This pins the ADF version. Ignore until we're sure the tests are actually passing (using the PR to test).
> SQL-1373: Pin ADF version

- evergreen.yml
I also changed hard-coded variant names to use ${build_variant} for copying to/from the mciuploads bucket because we had a bit of both and this could potentially become a problem if/when we change variant.
> SQL-1413: Copy signed msi to local folder instead of unsigned

- odbc/src/api/env_attr_tests.rs
- odbc/src/api/functions.rs
Working patch : https://spruce.mongodb.com/version/646241a33e8e8628c178bacb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> SQL-1285: SQLGetEnvAttr and SQLSetEnvAttr don't have Ansi/Wide flavors

- Cargo.toml
- DEVELOPER.md
- evergreen.yml
The custom "release-with-debug" profile is removed, and the "release" profile is now configured to include debug symbols
> SQL-1416: remove release-with-debug profile

- odbc/src/api/data_tests.rs
- odbc/src/api/functions.rs
- odbc/src/api/panic_safe_exec_tests.rs
The only functions that we implement that should not clear diagnostics are SQLGetDiagRec and SQLGetField (we don't implement SQLError).
I also set SQLAllocHandle and SQLFreeHandle to keep diagnostics to avoid any potential for calling unallocated memory, and freeing the handle is probably the ultimate way to clear diagnostics anyway.
Most of the changes are pretty mundane as I renamed the `panic_safe_exec` and that propagated everywhere.
> SQL-1439: clear diagnostics between odbc function calls

- core/src/util/test_connection.rs
- cstr/src/lib.rs
- odbc/src/api/data.rs
I refactored `odbc/api/data.rs` so that all instances of `copy_nonoverlapping` have been replaced with a helper function in `cstr`.
> SQL-1421: Refactor all ODBC string writing/reading to cstr

- evergreen.yml
dependencies correctly show up under snapshot, so should also show up for sign
https://spruce.mongodb.com/task/mongosql_odbc_driver_release_snapshot_patch_28437756461ac8bb86261d730efaf90ccfe4565d_648cba31c9ec444d557450c9_23_06_16_19_39_33/logs?execution=0
> update to use tags

- evergreen.yml
This ticket covers replacing uses of Notary Service with Garasign. In this ticket, I created a few new evergreen variables: `sql_engines_artifactory_username`, `sql_engines_artifactory_auth_token`, `release_tools_container_registry`, `odbc_garasign_username`, `odbc_garasign_password`, `garasign_jsign_image`, `garasign_gpg_image`. 
Two things I'm wondering about:
1. Despite the sign task for Windows running successfully, I see this error in the logs: `ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`. I'm not sure if this matters.
2. Should I create a signing verification step like in the tableau driver? There's nothing like this already in the `evergreen.yml`, so I'm not sure how …
> SQL-1448: Update signing tasks to use the new Garasign platform - ODBC driver

- odbc/src/api/data.rs
- odbc/src/api/functions.rs
Essentially, I renamed `set_str_length` to `set_data_length` and changed it to use generics. Then I called it in the places where `data_len_ptr` and `text_length_ptr` are set.
> SQL-1464: Check pointers before use

- core/src/odbc_uri.rs
This change makes the odbc driver report telemetry the same as the jdbc driver. I deleted the old test and introduced new tests to isolate the behavior for each condition.
> SQL-1554: handle telemetry data correctly

- Cargo.lock
- core/Cargo.toml
- integration_test/Cargo.toml
- odbc/Cargo.toml
- shared_sql_utils/src/dsn.rs
This PR bumps the rust driver version to 2.7.
I need to fix a `clippy` issue it looks like. I'll get on that.
> SQL-1708: Bump rust driver version to 2.7.x

- odbc/src/api/functions.rs
This PR removes the 200ms sleep after dropping the client. The ticket suggests this should be safe now that we've upgraded to rust driver 2.7.
> SQL-1265: Remove workaround for driver cleanup

- constants/src/lib.rs
- core/src/err.rs
- core/src/mock_query.rs
- core/src/query.rs
- odbc/src/api/col_attr_describe_tests.rs
- odbc/src/api/data.rs
- odbc/src/api/definitions.rs
- odbc/src/api/errors.rs
- odbc/src/api/functions.rs
- odbc/tests/connection_tests.rs
- Turns sql states into a list of length 2 to store both odbc 2 and odbc 3 sql states
- add odbc 2 to odbc version enum
- error if odbc 2 is set in SQLSetEnvAttr
> SQL-1684: Add enums to support ODBC 2.x

- odbc/src/handles/definitions.rs
- odbc/src/handles/unit.rs
This will enable functions to get the odbc version from any arbitrary handle passed in, i.e.,
```
let mongo_handle = MongoHandleRef::from(statement_handle);
let odbc_ver = mongo_handle.odbc_ver();
```
This can then be used to fork behavior based on odbc version -- namely in `SQLTables` and the `SQLGetDiag*` funcs.
> SQL-1685: add function to get odbc version from any mongo handle

- evergreen.yml
- integration_test/src/test_runner/mod.rs
- odbc/src/api/functions.rs
- odbc/tests/connection_tests.rs
Using `export RUSTFLAGS="-Z sanitizer=leak"` to enable ASAN for integration tests.  
The flag `"-Z sanitizer=address"` is more comprehensive but it was not compatible with the `serde_derive` crate and was throwing the following error:
```
[2023/11/22 12:13:38.048] error: /data/mci/97459366b05ed4c1edbb3e6d812cc9a7/mongosql-odbc-driver/target/debug/deps/libserde_derive-991a11b9bfb51463.so: undefined symbol: __asan_option_detect_stack_use_after_return
```
~~Tested that it does fail on memory leak by introducing a leak in SQLTablesW:~~
```
let leaked_memory = mem::transmute::<Box<i32>, *mut i32>(Box::new(42));
// also trying
let _leaked_memory = Box::leak(Box::new(42));
```
~~And confirming that the test failed due to the memory leak.~~ …
> SQL-1794: Enable ASAN for integration tests

- evergreen.yml
- integration_test/tests/odbc_2_tests.rs
- odbc-sys/src/sql_data_type.rs
- odbc/src/api/env_attr_tests.rs
- odbc/src/api/functions.rs
Followed a similar structure to power bi's flow. This is lightly borrowed but not directly taken from any particular odbc 2 flow, because they tend to do a lot of stuff in the middle (i.e., alloc the env handle, then make calls like SQLDrivers, SQLDataSources, SQLFunctions, etc) that weren't what we want to test here.
I instead tried hitting on the core odbc 2 behaviors (sql tables, sql get type info, connecting + getting data), with the SQLColumns to come as part of SQL-1688
> SQL-1690: enable odbc 2 to be set in SQLSetEnvAttr

- setup/setupDSN.reg
- shared_sql_utils/src/dsn.rs
- win_setupgui/src/gui.rs
This allows the log level to be written / read properly, so that the odbc configuration (set via dsn, or registry file) will be used by the driver.
Ubuntu tests are failing, but appears to not be related -- periodic build started failing 12/29: https://spruce.mongodb.com/variant-history/mongosql-odbc-driver/ubuntu2204?selectedCommit=521
> SQL-1850: add LogLevel to dsn iterator

- constants/src/lib.rs
- odbc/src/api/data.rs
This PR updates the `data.rs` unit tests to directly compare `OdbcState`s. To achieve this, we derive `PartialEq, Debug, Copy, Clone` on the `OdbcState` type.
> SQL-1828: Directly compare OdbcStates in data.rs unit tests

- Cargo.lock
- DEVELOPER.md
- core/Cargo.toml
- core/src/util/test_connection.rs
- evergreen.yml
- integration_test/Cargo.toml
- integration_test/src/test_runner/mod.rs
This PR updates the result set tests to use feature flags instead of the `#[ignore]` attribute. Before this PR, only 3 test functions used the `#[ignore]` attribute -- two of them are `resultset_tests` and `odbc2_resultset_tests`. Those two tests have been updated to use the `#[cfg(features = "result_set")]` attribute. There is also the the `bad_host` test [here](https://github.com/mongodb/mongo-odbc-driver/blob/78610f8d3b4112cef27566d44442e19374ee69cf/core/src/util/test_connection.rs#L113) that was seemingly run _unintentionally_ as part of the result set test tasks. I have not updated that one since it looks like we actually do mean to ignore it. Let me know if that is not the case.
> SQL-1915: Switch to feature flags instead of ignore for tests

- definitions/src/desc.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/functions.rs
These connection and column attributes allow for SSMS to relay correct errors with a query (both from the application and driver side). Previously, it would output cached errors caused by these.
> SQL-1867: implement additional connection attributes

- resources/run_adf.sh
Sets to an ADF version prior to the changes to require configuration values. 
Passing tests:
https://evergreen.mongodb.com/version/65f0858c1e2d1742684714e4
> SQL-1975: Set working ADF version in run_adf to pass integration tests

- resources/integration_test/config/adf_config.yaml
- resources/run_adf.sh
Added  `currentOp:` and `query: killOp:` configuration  to the latest [ADF config](https://github.com/10gen/mongohouse/blob/master/testdata/config/inline_local/frontend-agent-backend.yaml) for inline_local. 
@pmeredit the ADF config for the ODBC repo has changes to enable match filters after currentOp that Jonathan added.  This config is different from the JDBC/Power BI repos so that could be one reason to keep the run_adf scripts separate.
> SQL-1976: Update ADF config to add new required values

- integration_test/src/test_runner/mod.rs
- integration_test/tests/common/mod.rs
- integration_test/tests/connection_tests.rs
- integration_test/tests/free_and_cancel_tests.rs
- integration_test/tests/odbc_2_tests.rs
- integration_test/tests/power_bi_tests.rs
- integration_test/tests/prepared_statement_tests.rs
This PR adds integration tests for the SSIS preview data flow. I broke it down into two tests since SSIS has a tendency to free all handles between discrete units of work. As discussed individually, I attempted to make these tests _slightly_ more general than the exact SSIS workflow. Instead of naming them "ssis_tests" I called the file "free_and_cancel_tests.rs" since this is the first set of integration tests that focus on the newly implemented `SQLFreeStmt` and `SQLCancel` functions. I am open to modifying the names/coverage as requested.
> SQL-1962: Add integration tests for SSIS preview data flow

- core/src/bin/test_oidc_call_back.rs
- core/src/bin/test_oidc_call_back_short_timeout.rs
- core/src/bin/test_oidc_call_back_with_bad_refresh_token.rs
- core/src/oidc_auth.rs
Note that this also handles the timeout. The test function with timeout works on my laptop. I'm still waiting forever and a half for my desktop harddrive to finish encrypting, but I imagine it will work on windows, also.
> SQL-1933: Add oidc_call_back function

- integration_test/tests/bind_cols_tests.rs
- integration_test/tests/common/mod.rs
- integration_test/tests/free_and_cancel_tests.rs
This PR adds an integration test for the SSIS query flow. ~This builds on top of #194. Feel free to ignore the first commit -- for convenience, I'll rebase it away once #194 is merged into master.~
I created just one test since really only one unique new behavior is done by running a query in SSIS. The test calls `SQLBindCol` after executing a query, and calls `SQLFreeStmt` after those calls to `SQLBindCol`. This is different from the previous `SQLFreeStmt` test since the previous one did not bind columns prior to freeing the statement.
This is optionally blocked on #192 since I set the `ROW_ARRAY_SIZE` attribute to 1000 (just like SSIS). Technically, I can omit that and we can observe this test passing now. I figure it is ok to leave this in review until after #192 is merged, though.
> SQL-1964: Add integration tests for SSIS query flow

- evergreen.yml
Adding a comment to avoid the logic being undone later on
> SQL-2037: Explain why the logger tests run in isolation 

- evergreen.yml
- Generate the SBOM Lite and augment it with vulnerabilities.
- Copy SBOM to S3
- Scan, using the list of allowed vulns to filter vulnerabilities to ignore.
Here is a run without filtering vulnerabilities : https://spruce.mongodb.com/task/mongosql_odbc_driver_code_quality_security_sbom_patch_40ad9d02424a297f5baae4657fd2d869cd2bcc17_665ee0bb98f4ac0007ae4589_24_06_04_09_39_23/logs?execution=0
Both are vulns with no known fix.
> SQL-2092: Generate and scan SBOM

- win_setupgui/src/gui.rs
This updates the effective display size of the column containg the maximum string length setting by altering the column count the text is allowed to fill.
> SQL-2135: update display size of column

- core/src/bson_type_info.rs
- core/src/type_info.rs
This PR updates the `BsonTypeInfo.non_concise_type` field to be optional.
> SQL-1999: Update BsonTypeInfo.non_concise_type to be an Option

- odbc/src/api/free_stmt_tests.rs
- odbc/src/api/functions.rs
This PR updates `SQLFreeStmt` to handle the case when the `FreeStmtOption` is `SQL_CLOSE` and `mongo_statement` is `None`. Previously, we would return an error that wrapped a panic. Now, we no-op. I added a unit test to demonstrate we no longer panic/error.
> SQL-2066: Update SQLFreeStmt to check that mongo_statement exists before closing cursor

- evergreen.yml
Successful run: https://spruce.mongodb.com/task/mongosql_odbc_driver_release_trace_artifacts_test_patch_40ad9d02424a297f5baae4657fd2d869cd2bcc17_666a1af864e1ae0007c8faac_24_06_12_22_02_44/logs?execution=0
Producing the following (testing) trace: https://papertrail.devprod-infra.prod.corp.mongodb.com/product-version?product=mongo-odbc-driver-testing&version=666a1af864e1ae0007c8faac
> SQL-2104: add papertrail tracing to odbc

- evergreen.yml
- resources/ssdlc/mongo-odbc-driver_compliance_report_template.md
example patch: https://spruce.mongodb.com/version/6675e88c1a4be000079017d2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
creates a compliance report: https://translators-connectors-releases.s3.amazonaws.com/mongosql-odbc-driver/mongosql-odbc-snapshot-compliance-report.md
Followed the same template used by bic / provided by devprod, removed security testing section
> SQL-2106: Add compliance report for odbc driver

- evergreen.yml
- installer/dmg/build-dmg.sh
- installer/msi/LicensingFragment.wxs
Moved the pulling of sbom from silk to so it will be in mciuploads; then, we can pull prior to building msi/tarring linux artifacts.
> SQL-2109: publish 3rd party dependency report for ODBC

- evergreen.yml
This adds the appropriate s3.get to the publish SBOM task, which was missed because the evergreen settings caused ssdlc tasks not to be scheduled. Those have now been updated as well, as can be seen via the evergreen patch.
> SQL-2109: fix evergreen script

- resources/run_adf.sh
Syncing changes made to `run_adf.sh` in the mongo-jdbc-driver repo.
> SQL-2244: Add Linux ARM support in run_adf.sh

- Cargo.lock
- core/Cargo.toml
- cstr/Cargo.toml
- definitions/Cargo.toml
- evergreen.yml
- integration_test/Cargo.toml
- logger/Cargo.toml
- macos_postinstall/Cargo.toml
- odbc/Cargo.toml
Sanitizing task and work for odbc. Here the `--all-features` trick doesn't work because some of the features enable things that aren't compatible with all systems. [Here is a patch](https://spruce.mongodb.com/version/66b6501b76d45c000746d996/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) showing failure because of an unused dependency.
> SQL-2272: sanitize deps

- core/src/cluster_type.rs
- core/src/conn.rs
- core/src/err.rs
- core/src/lib.rs
- core/src/util/test_connection.rs
- evergreen.yml
- integration_test/Cargo.toml
- integration_test/tests/cluster_type_test.rs
- odbc/src/api/functions.rs
- resources/start_local_mdb.sh
Adds change to check whether the cluster connected to is community edition, enterprise, or ADF.  
Removes the `SELECT 1` query and instead uses the check for buildinfo. 
Added integration test that has a script to start `mongod` community and enterprise versions taken from `mongo-jdbc-driver` repo.
> SQL-2290: Differentiate between cluster types on connection

- evergreen.yml
- resources/run_adf.sh
Copying changes from the [mongo-jdbc-repo](https://github.com/mongodb/mongo-jdbc-driver/pull/283) over. 
Running test on host without ssh keys [here](https://spruce.mongodb.com/version/66e8c5754198dd000734ee38/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&statuses=success).
>  SQL-2299: Use github token for cloning instead of ssh

- evergreen.yml
Also added changes for Silk upload to work described in [SQL-2322](https://jira.mongodb.org/browse/SQL-2322)
> SQL-2312: Migration of Evergreen Static Host Fleets to Secure Private Data Centers

- evergreen.yml
Local testing:
```
➜  ~ echo $triggered_by_git_tag
v1.2.3-libv4.5.6
➜  ~ export RELEASE_VERSION=$(echo ${triggered_by_git_tag} | cut -d'-' -f1 | sed s/v//)
➜  ~ export LIBMONGOTRANSLATE_VERSION=$(echo ${triggered_by_git_tag} | cut -d'-' -f2 | sed s/libv//)
➜  ~ echo $RELEASE_VERSION
1.2.3
➜  ~ echo $LIBMONGOTRANSLATE_VERSION
4.5.6
```
> SQL-2396: parse libmongotranslate version

- evergreen.yml
Note: parsing of libmongotranslate version was done in a preceding pr so both Patrick and I can access it.
Updated all references to mongoodbc.msi and mongoodbc.tar.gz to just use the versioned filename to avoid any confusion.
> SQL-2396: update evergreen file

- evergreen.yml
Patch showing the ubuntu signing task passing: https://spruce.mongodb.com/version/671ff639fc46880007190ff4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> SQL-2420: Fix ubuntu signing task for on-prem-eap branch

- core/src/conn.rs
- odbc/src/api/functions.rs
Switching out `get_adf_version` for `get_server_version`. Datalake is now optional so it's universal. If for some reason the command fails it'll be automatically handled.
> SQL-2422: replace get_adf_version

- core/src/err.rs
- core/src/mongosqltranslate.rs
- evergreen.yml
I had trouble rebasing my [previous PR ](https://github.com/mongodb/mongo-odbc-driver/pull/252) which is already approved.  It was initially pointing to the wrong branch so I am opening this. 
Removes the hard-coded values and uses the driver property from DriverSettings to get the directory of the ODBC driver.
>  SQL-2403: Obtain path for mongosqltranslate lib from DriverSettings

- docs/overview.md
- evergreen.yml
This updates the paths in the release to be prepended with "eap".
Additionally, the release version and libv version are fetched slightly differently now.
Most of the changes to the evergreen file are auto formatting, with extraneous spaces removed.
It apears I targeted the docs at the wrong base (master), so they all appear here. The only additions from the approved #253  are "Escape Fields" under ## Usage, and ##### Prerequisites under #### Windows Installation
> SQL-2428: update to proper paths

- evergreen.yml
Validating our evergreen file there were warnings that this cleans up. I'm still trying to figure out why the [release process is failing](https://spruce.mongodb.com/version/mongosql_odbc_driver_eap_v2.0.0_alpha_libv1.0.0_alpha_1_672ccc6682ee320007eee133/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC), even though I can do a patch release and it works fine.
> fixing some yaml warnings

- core/src/query.rs
I struggled to find a clean way to get a list of databases to the schema pulling, so rather, I just used the client to pull all databases at the time of querying. The reason it was an issue is that we create new HDbc handles, and MongoConnections, frequently enough that the only way to persist the databases from the initial listing was to push all the way down to the env handle (which didn't seem right). I'm very open to alternative implementations if there's an easier way!
I also needed to update the db set on the MongoQuery returned from mongoprepare in order to get the execute function working properly.
This seems to work in power bi, though would love a second set of eyes in case I missed anything!
> SQL-2466: handle changing databases for power bi on prem

- evergreen.yml
The rust toolchain needed to be added. The integration test issue was due to someone writing to the source database, and happening to write to the exact collection we expect not to exists.
https://spruce.mongodb.com/version/6734d908150c5700079b6c79/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Add rust toolchain

- constants/src/lib.rs
- odbc/src/api/functions.rs
This PR adds support for `InfoType::SQL_KEYWORDS` by returning a `lazy_static` string representing MongoSQL-specific keywords. I took the `mongosql-rs` list of keywords ([here](https://github.com/10gen/mongosql-rs/blob/921ea1b6df6d2d9df360c12bcd49a46acddadacc/mongosql/src/parser/mongosql.lalrpop#L754)) and removed anything already included in the [ODBC Reserved Keywords list](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/reserved-keywords?view=sql-server-ver16).
> SQL-2499: Add support for InfoType::SQL_KEYWORDS

- core/src/mongosqltranslate.rs
- core/src/util/mod.rs
- core/src/util/test_connection.rs
- cstr/src/lib.rs
- definitions/src/desc.rs
- odbc/src/api/functions.rs
This addresses the following JIRAs in the main branch, and is a carbon copy of the fixes introduced in PR #276 
- SQL-2496: handle null pointer parameters in SQLTablesW
- SQL-2497 handle null pointer parameters in SQLColumnsW
- SQL-2500: treat emptry string as no filter in table_type_filter_to_vec
- SQL-2505: address clippy warnings/errors that are causing the waterfall to not be green
> SQL-2502: port from other PR

- evergreen.yml
This commit templates our authenticode key name in preparation for the authenticode 2021 deprecation. The variable will be added to our Evergreen project as mongo-authenticode-2024.
> DEVPROD-13313: template authenticode key name

- constants/src/lib.rs
- odbc/src/api/functions.rs
* SQL-2499: Add support for InfoType::SQL_KEYWORDS
* SQL-2499: Remove ORDER keyword
> SQL-2499: Add support for InfoType::SQL_KEYWORDS (#277)

- integration_test/src/test_runner/mod.rs
- integration_test/tests/cluster_type_test.rs
- integration_test/tests/common/mod.rs
- integration_test/tests/connection_tests.rs
- integration_test/tests/disconnect_tests.rs
- odbc/src/api/functions.rs
Add null checking for `string_length_2` in the `SQLDriverConnectW()` function. 
This allowed the `iusql -v MongoDB_Atlas_SQL` command on Ubuntu to succeed. 
```
$ iusql -v MongoDB_Atlas_SQL
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> 
```
Added a test to confirm that the connection works with the `string_length_2` parameter is null and confirmed the test fails without the change.
> SQL-2527: Handle possible null string_length_2 parameter

- Cargo.lock
- Cargo.toml
- constants/Cargo.toml
- core/Cargo.toml
- cstr/Cargo.toml
- definitions/Cargo.toml
- integration_test/Cargo.toml
- logger/Cargo.toml
- macos_postinstall/Cargo.toml
- mock_mongosqltranslate/Cargo.toml
- odbc/Cargo.toml
- odbc/src/api/data.rs
- odbc/src/api/errors.rs
- rfc8252_http_server/Cargo.toml
- shared_sql_utils/Cargo.toml
- win_setupgui/Cargo.toml
I cherry-picked the recently merged commit on the master branch that moves duplicated dependencies to workspace dependencies.
> SQL-2528: Move to workspace dependencies in odbc on-prem-eap branch

- evergreen.yml
- evergreen/generate_licenses.sh
- installer/msi/LicensingFragment.wxs
- resources/third_party_header.txt
This adds the 3rd party notices to both the linux distributable tar and the windows msi.
It will in fact regenerate them every time, but I've also included a (static) one that we can update from time to time for compliance.
> SQL-2533: add third party notices

- Cargo.lock
- odbc/src/api/functions.rs
Fix for the ASAN test failure. 
I also added an update to the `openssl` dependency since it was failing the `sbom` check.
@EthanHardyMongo The fix I mentioned to you for the sbom failure is here, I ran `cargo update -p openssl` to update it.
> SQL-2615: Add null check for handle in panic_safe_exec_keep_diagnostics

- evergreen.yml
This is cherry-picked from master.
> Add `retry_on_failure: true` to ODBC MacOS compile and unit test functions

- odbc/src/api/functions.rs
- odbc/src/api/panic_safe_exec_tests.rs
- odbc/src/handles/definitions.rs
- odbc/src/handles/unit.rs
Switched `From<Handle>` to `TryFrom<Handle>`. 
Updated the uses to use a macro `try_mongo_handle!` that checks for error, if so returns `SqlReturn::INVALID_HANDLE`.
Added unit test.
> SQL-2615: Switch handle conversion to TryFrom to handle null values

- Cargo.lock
- definitions/src/c_data_type.rs
- integration_test/tests/odbc_2_tests.rs
- odbc/src/api/bind_col_tests.rs
- odbc/src/api/data.rs
This PR adds missing C Data types that were deprecated in `ODBC 3*.x*`.
From the ODBC spec: 
```
SQL_C_SHORT, SQL_C_LONG, and SQL_C_TINYINT have been replaced in ODBC by signed and unsigned types: 
SQL_C_SSHORT and SQL_C_USHORT, SQL_C_SLONG and SQL_C_ULONG, and SQL_C_STINYINT and 
SQL_C_UTINYINT. An ODBC 3*.x* driver that should work with ODBC 2.x applications should support SQL_C_SHORT, 
SQL_C_LONG, and SQL_C_TINYINT, because when they are called, the Driver Manager passes them through to the 
driver.
```
> SQL-2546: Add missing c data types to odbc enum

- Cargo.lock
All I did was `cargo update`. I'll cherry-pick to on-prem-eap once this is merged.
> SQL-2689: Fix ODBC Driver build failure due to vulnerability in "ring" package

- core/src/err.rs
- core/src/lib.rs
- core/src/query.rs
- odbc/src/api/data_tests.rs
- odbc/src/api/functions.rs
- odbc/src/handles/definitions.rs
I ended up reworking this to put the diagnostic info on the connection, where it was more easily accessible in the odbc layer.
If the error occurs on a connection or statement, the diagnostics are read from the corresponding MongoConnection and logged at error level.
There is also a  debug level logging event in prepare. I ended up going with debug because trace is very noise, and we'd probably ask for debug logs first.
> SQL-2660: additional logging for ODBC

- Cargo.lock
- evergreen.yml
- odbc/src/api/data.rs
I also:
- ran cargo update, so the lockfile changed
- fixed a new error about type information being needed
> SQL-2714: get latest mongosql tag in evergreen

- Cargo.lock
- core/Cargo.toml
- core/src/query.rs
- evergreen.yml
- odbc/src/handles/definitions.rs
Due to changes in mongosql we find ourselves in this interim state. @jchemburkar you will probably want to file another ticket as soon as the rest of derivation is in and released, otherwise it will break again.
Clippy also highlighted that the Statement variant of a MongoHandle is quite large. I took a quick pass at it but there are memory management implications that need to be more thought out.
> SQL-2830: Enable building of eap

- evergreen.yml
Runs the windows signing task on the Ubuntu host instead of Windows. 
Working patch:
https://evergreen.mongodb.com/task/mongosql_odbc_driver_eap_windows_64_sign_patch_b6173da8984297d390eaea0eb790116767141bd8_683e726bfba74c000791fd6b_25_06_03_03_56_56
> SQL-2846: Fix Windows signing for standard build

- evergreen.yml
- evergreen/create-expansions.sh
- evergreen/eap.yml
- resources/download-center/mongo-odbc-downloads_template.json
The sbom release [task](https://spruce.mongodb.com/task/mongosql_odbc_driver_eap_code_quality_security_sbom__v2.0.0_beta_4_libv1.0.0_beta_5_25_06_17_23_10_15/logs?execution=0) failed. The implication of the error message (generated [here](https://github.com/mongodb/sql-engines-common-test-infra/blob/db60f9fbdcf8e1a9154ac647b94cdb81ecf1c431/evergreen/scripts/set_and_check_packages_version.sh#L23)) is that the `$release_version` variable is empty, and that it was successfully picked up as triggered by git tag. So I think this is just a result of variable case sensitivity, but let me know if there is a better idea. 
I didn't see obvious implications for other variables in a brief scan. I believe this is coming up because it is the first time releasing ODBC since switching over to the shared …
> SQL-2868: update RELEASE_VERSION

- Cargo.lock
- Cargo.toml
- core/src/odbc_uri.rs
- evergreen.yml
- evergreen/create-expansions.sh
- installer/msi/build-msi.ps1
This PR adds support for the GSSAPI auth mechanism by updating the Rust driver to 3.3.0 and handling the user provided password on non-Windows platforms.
> SQL-2873: Add support for GSSAPI auth mechanism
