- core/Cargo.toml
- odbc/Cargo.toml
No changes required other than updating Cargo manifests
> SQL-650: Update to rust 2021 edition

- core/src/collections.rs
- core/src/databases.rs
- core/src/fields.rs
- core/src/query.rs
- core/src/stmt.rs
- odbc/src/api/functions.rs
- odbc/src/handles/definitions.rs
Implemented functions for `MongoDatabases` and made a call to `list_all_catalogs()` in `sql_tables`.
Open question: how do we plan to unit test this and upcoming functionality that retrieve results from the database?
> SQL-635: Implement database listing logic

- odbc/src/api/data.rs
I simplified the string conversion to the same logic as floats since the conversion chart had the same tests.
> SQL-1096: audit to_bit

- LICENSE
Adding the same license we use for jdbc
> SQL-651: add license file

- core/src/json_schema.rs
This PR simplifies schemas that are AnyOf one concrete type that we have the ability to show.
> SQL-1168: Simplfiy Anyof(<one>) and double buffer

- README.md
- odbc/src/api/data.rs
- odbc/src/api/diag.rs
- odbc/src/api/functions.rs
Where to find the list of W functions => https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode-function-arguments
> SQL-1285: Remove ANSI endpoint

- core/src/conn.rs
- core/src/lib.rs
- core/src/query.rs
- core/src/util/test_connection.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/functions.rs
- odbc/src/handles/definitions.rs
Turns out we supported getting this attribute in SQLGetConnectAttrW but never implemented setting it via SQLSetConnectAttrW.
> SQL-1434: Support setting SQL_ATTR_CURRENT_CATALOG

- core/src/collections.rs
- core/src/databases.rs
- core/src/fields.rs
I've opened a ticket with ADF, and commented the ticket number above the relevant lines I added.
> SQL-1440: filter out admin and empty strings

- evergreen.yml
Basically, I took all the same tasks that were made for each variant and merged them into a more general task (e.g., `windows_unit_test`, `ubuntu_unit_test`, etc. merged into `unit_test`).
> SQL-1334: Clean up ODBC evergreen file

- core/src/conn.rs
- core/src/lib.rs
- core/src/query.rs
- core/src/util/test_connection.rs
- integration_test/tests/power_bi_tests.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/data.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_info_tests.rs
- odbc/src/handles/definitions.rs
A lot of this is reverting my previous implementation of supporting current_catalog. I've gone with a much simpler approach in this. I have verified that this no longer hangs with the new build of the BI tool and the trouble query.
> SQL-1457: fix hanging rwlocks

- core/Cargo.toml
- core/src/odbc_uri.rs
- integration_test/Cargo.toml
- odbc/Cargo.toml
- odbc/src/api/functions.rs
Wait to see if the tests pass. I didn't feel like setting up the integration tests locally :joy:
> SQL-1529: Rust Driver 2.6.0

- evergreen.yml
> SQL-1548: re-enable macos11 arm tests

- odbc/src/api/data.rs
- odbc/src/api/diag.rs
- odbc/src/api/errors.rs
- odbc/src/api/functions.rs
- odbc/src/api/get_diag_field_tests.rs
- odbc/src/api/get_diag_rec_tests.rs
- odbc/src/api/get_type_info_tests.rs
Uses the odbc version to return the proper odbc 2/3 sqlstate
> SQL-1687: return correct sqlstate from get diag funcs

- evergreen.yml
This is analogous to the powerbi connector fix
> SQL-1839: Fix Download Center JSON feed

- core/src/mock_query.rs
- core/src/query.rs
- core/src/stmt.rs
- definitions/src/lib.rs
- odbc/src/api/free_stmt_tests.rs
- odbc/src/api/functions.rs
- odbc/src/api/mod.rs
- odbc/src/handles/definitions.rs
This PR implements `SQLFreeStmt` according to the guidelines in the design doc.
> SQL-1864: Implement SQLFreeStmt

- odbc/src/api/data_tests.rs
- resources/run_adf.sh
Just a small one adding tests to ensure we're fetching decimal128 values correctly!
> SQL-2000: decimal128 tests

- core/src/bson_type_info.rs
- core/src/col_metadata.rs
- resources/integration_test/tests/functions.yml
- resources/run_adf.sh
This way a truly NULL column isn't interpreted as an unknown type.
> SQL-2009: simple  types for null

- evergreen.yml
patch with sbom task which will push sbom to silk and then pull it back: https://spruce.mongodb.com/task/mongosql_odbc_driver_code_quality_security_sbom_patch_dacf6b588115422b6d2cfff8262e4ee9f40efec1_6674c648809c1f0007f8c47b_24_06_21_00_16_20/files?execution=0
augmented sbom: https://translators-connectors-releases.s3.amazonaws.com/mongosql-odbc-driver/mongosql-odbc-snapshot.sbom.json
> SQL-2099: add silk integration for odbc

- evergreen.yml
passing run with current commits: https://spruce.mongodb.com/version/66f5da63bf883a0007f6b518/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> SQL-2079: remove compile-debug

- docs/overview.md
- evergreen.yml
> SQL-2384: ODBC Documentation

- evergreen.yml
- evergreen/make_docs.sh
- installer/dmg/build-dmg.sh
- installer/msi/LicensingFragment.wxs
Tasks to publish docs. I also commented out sbom  stuff for the eap.
> SQL-2386: evergreen tasks to publish docs

- evergreen.yml
No idea why it was put in there differently. Alas.
> fix var name

- evergreen.yml
Also updating here to macos-11
> update hosts on master

- core/src/odbc_uri.rs
Overall the changes are relatively small. A couple new helper functions to make it easy. If there is no authMechanism specified, or if the authMechanism is one of the Scrams or PLAIN, then username and password are injected if not there already. Otherwise, it's fine to send along for parsing by the driver.
> SQL-2486: inject username and password into uri for parsing if required

- definitions/src/lib.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/functions.rs
- odbc/src/handles/definitions.rs
- odbc/tests/connection_tests.rs
I tested this with Microstrategy using the instructions in the doc. It seems to work as expected, or at least, I do not see any of the previously mentioned errors in the logs.
I did not test this wiht Qlik View because the doc does not contain instructions to set it up, and there seems to be other blockers for that tool as well.
> SQL-2501: Implement additional column attributes

- core/src/odbc_uri.rs
Copying in what I did for #269 and #275 to support x509 and get rid of uri quirkiness
> SQL-2474: make same changes from #269

- definitions/src/lib.rs
- odbc/src/api/connect_attr_tests.rs
- odbc/src/api/functions.rs
- odbc/tests/connection_tests.rs
Copying changes from eap branch
> SQL-2501: add connection attributes

- core/src/odbc_uri.rs
After looking at Natacha's PR for Java and speaking with her, I realized I should not be modifying URIs that do not have an authMechanism explicitly set. This will work for implicit SCRAM as well as authless connections.
> do not modify uri if no mechanism explicitly set

- integration_test/src/test_runner/mod.rs
- integration_test/tests/cluster_type_test.rs
- integration_test/tests/common/mod.rs
- integration_test/tests/connection_tests.rs
- integration_test/tests/disconnect_tests.rs
- integration_test/tests/mongosqltranslate_tests.rs
- odbc/src/api/functions.rs
Cherry-picked commit from the master branch to handle the segmentation fault in iusql.
> SQL-2527: Handle possible null string_length_2 parameter

- Cargo.lock
- odbc/src/api/functions.rs
This change is cherry-picked from the `master` branch
> SQL-2615: Add null check for handle in panic_safe_exec_keep_diagnostics

- odbc/src/api/functions.rs
- odbc/src/api/panic_safe_exec_tests.rs
- odbc/src/handles/definitions.rs
- odbc/src/handles/unit.rs
Cherry picked from the master branch into `on-prem-eap` branch.
> SQL-2615: Switch handle conversion to TryFrom to handle null values 

- core/src/json_schema.rs
- core/src/odbc_uri.rs
I also ran `cargo +nightly clippy` and implemented the suggestions it made for json_schema.
I'll cherry-pick this to on-prem-eap once merged.
> SQL-2662: apply clippy suggestions to ODBC

- evergreen.yml
Silkbomb 2.0 introduces the `augment` command which will allow you to upload your sbom to be scanned by OSV and have an augmented SBOM returned with any vulnerabilities in a single step. 
Let me know if I'm missing anything or if there is anything else that can be cleaned up or improved. Thanks!
> update to silkbomb 2.0

- evergreen.yml
This is cherry-picked from master.
> Cherry-pick 'update to silkbomb 2.0'

- evergreen.yml
Once merged, I'll cherry-pick to `on-prem-eap`
> SQL-2679: Fix Windows build failure due to rustup update

- Cargo.lock
This is cherry-picked from master.
> SQL-2689: Fix ODBC Driver build failure due to vulnerability in "ring" package

- odbc/src/api/data.rs
It was folly to blindly use expect here, my bad. With the addition of these helper functions we'll generate an ODBCError instead of panicking.
> SQL-2695: safely handle date, time, and datetime construction

- evergreen.yml
Also requested a review from copilot to see what it does.
> SQL-2728: Update to use git ls-remote

- core/src/col_metadata.rs
- core/src/err.rs
Cherry picked changes from main
> SQL-2781 : Handle empty select list

- docs/overview.md
Updates for the new syntax. I'll copy this over to jdbc too, once approved.
> chore: update overview to include unwind updates

- core/src/collections.rs
- core/src/util/mod.rs
- evergreen.yml
- integration_test/tests/common/mod.rs
- integration_test/tests/power_bi_tests.rs
This change was not fast because it took a very long time to actually repro the error. The error could not be reproed on a local mongod because apparently local mongod does not return an Error in this case whereas ADF does. After I realized that, I needed to figure out how to actually create users in a local ADF... which took awhile.
The change itself took 2 seconds, and worked first try, of course :joy:
> SQL-2909: Fix sharp edge in ADF collection listing
